kind: PersistentVolume
apiVersion: v1
metadata:
  name: akkc-pv
spec:
  capacity:
    storage: 10Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: /akkc



# Yahan pe hum local PV bana rhe hn, jo Node(HostNode) ka storage use karta h.
