apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: akkc-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: manual   # ye PV aur PVC dono me same hona chahiye
  resources:
    requests:
      storage: 10Mi

